### ISSUE TITLE
Hactoberfest-2023

### ISSUE THREAD

**Issue by shishirkj** [lazyjinchuriki/portfolio#1]
hi i would like to contribute here and help improving your portfolio ,any suggestions ?

**Comment by lazyjinchuriki** [comment]
Hi there!
Glad you're interested in my project. 😊 
Some suggestions are:
1. Subscribe to Newsletter feature
2. Improved Navbar in Mobile View (good first issue)
3. Change the tabs layout and make it more appealing.

You can add another section, If you like.
Best of Luck.👍🏻
and feel free to contact me for any further query.

**Comment by Adityakr55** [comment]
Please assign me this issue.

**Comment by lazyjinchuriki** [comment]
> Please assign me this issue.

Fork this project, clone it to your personal machine make necessary changes make a pull request..I'll merge it and you'll have 1 pull request merged for hactoberfest.

**Comment by krn1904** [comment]
Is this issue assigned to anyone? if not then i would like to do it.
