### ISSUE TITLE
making the navbar glassmorphic 

### ISSUE THREAD

**Issue by NateNear** [lazyjinchuriki/portfolio#17]
![image](https://github.com/lazyjinchuriki/portfolio/assets/92938055/418e7fa0-592f-49ad-af14-aaa2c0f83c13)

### making the navbar like this

![image](https://github.com/lazyjinchuriki/portfolio/assets/92938055/f9fa4943-779e-4ef0-b237-19d539309777)

**Comment by lazyjinchuriki** [comment]
Sure. That looks good!

**Comment by aryankshl** [comment]
hey @NateNear , can you assign this to me?

**Comment by Vishusingh16** [comment]
can you assign me this issue?
