### ISSUE TITLE
Texts in the navbar are overflowing at 900 to 950px screen widths.

### ISSUE THREAD

**Issue by Abhishek-465** [lazyjinchuriki/portfolio#2]
**Description**: Texts in the navbar are overflowing at 900 to 950px screen widths.
**Steps to reproduce**:
1. Open the home page of the website.
2. If you are in desktop then resize the screen and set between 900 to 950 px.
3. Clearly the texts are overflowing and conflicting with the link elements.

I have started working on this issue and i am going to fix it as soon as possible.

![Screenshot (13)](https://github.com/lazyjinchuriki/portfolio/assets/127030695/7216f06e-c4ae-4ea0-90ee-619e1185eacf)

**Comment by lazyjinchuriki** [comment]
I wish you the best.👍🏻
