### ISSUE TITLE
Create Contributing.md

### ISSUE THREAD

**Issue by i-am-yuvi** [lazyjinchuriki/portfolio#23]
**This is a(n):**
- [ ] Update to an existing code
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
I would like to create a CONTRIBUTING.md file so that newcomers can understand the basic principles of contributing to the repositories and other related information.

**Comment by lazyjinchuriki** [comment]
Sure thing.

**Comment by Rohxn16** [comment]
Hey I would like to work on this issue.

**Comment by Rohxn16** [comment]
@lazyjinchuriki I have done a pull request to solve this issue please review [https://github.com/lazyjinchuriki/portfolio/pull/41](url)
