### ISSUE TITLE
Adding hover effect on skills cards.

### ISSUE THREAD

**Issue by NateNear** [lazyjinchuriki/portfolio#26]
![image](https://github.com/lazyjinchuriki/portfolio/assets/92938055/598ab2dc-5a5d-40d4-be35-d5e3f4538b88)

### to something like this.

![image](https://github.com/lazyjinchuriki/portfolio/assets/92938055/9f14f9da-a432-4daa-9f2e-3165038dd233)

**Comment by lazyjinchuriki** [comment]
How it looks in mobile view?

**Comment by NateNear** [comment]
### Like this..

![image](https://github.com/lazyjinchuriki/portfolio/assets/92938055/2275a7cb-775c-4837-874b-308aa43dd2a2)

**Comment by lazyjinchuriki** [comment]
It's fine but the carousel should be there.
Create a PR I'll merge it
