### ISSUE TITLE
Animations are too fast

### ISSUE THREAD

**Issue by AbubakarImam** [lazyjinchuriki/portfolio#29]
Image animation of the image beside the contact form is too spontaneous and most of the other animations to

**Comment by lazyjinchuriki** [comment]
Can you fix that?

**Comment by AbubakarImam** [comment]
Yes

**Comment by AbubakarImam** [comment]
i have been having serious errors installing the project on my local machine

**Comment by soniyaprasad77** [comment]
Let me proceed for this issue. @AbubakarImam @lazyjinchuriki

**Comment by harmit17** [comment]
Hey @lazyjinchuriki, can you assign it to me if no one is working on it? I plan to make the animation slower and reduce the size of the image a little.

**Comment by harmit17** [comment]
Hey @lazyjinchuriki, you can review the pull request.
