### ISSUE TITLE
Navbar issue on some dimension

### ISSUE THREAD

**Issue by uditpadhan98** [lazyjinchuriki/portfolio#31]
The navbar is looking weird in some dimensions.
Can I work on this to fix it?
<img width="591" alt="Screenshot 2023-10-12 142442" src="https://github.com/lazyjinchuriki/portfolio/assets/105899769/f9036525-9980-461f-96e8-93e3136267c9">

**Comment by lazyjinchuriki** [comment]
No need. Already someone is working on that.
