### ISSUE TITLE
Bad UI for Navbar

### ISSUE THREAD

**Issue by rhnas110** [lazyjinchuriki/portfolio#33]
Hi Sir @lazyjinchuriki 
Issue Description:
UI Navbar is not centered and not precise enough, and the text PORTFOLIO in the navbar cannot be clicked, it can only be clicked on the letter P.

Before:
![image](https://github.com/lazyjinchuriki/portfolio/assets/51848196/93b3c557-40e1-4d15-a84a-db5e42030582)

After:
I can fix  text PORTFOLIO href issue and I want to improve your navbar to make it better.

Can you take my advice and assign this task to me Sir @lazyjinchuriki ? and I'm actually new to open source contributions, I also participated in Hacktoberfest2023.

**Comment by lazyjinchuriki** [comment]
Sure thing buddy.
