### ISSUE TITLE
Bug: In mobile view the send button in contact section is still recatangular

### ISSUE THREAD

**Issue by soniyaprasad77** [lazyjinchuriki/portfolio#34]
![Screenshot (235)](https://github.com/lazyjinchuriki/portfolio/assets/63783532/6e097913-e2c4-4e92-ac69-492b02909d61)

**Comment by lazyjinchuriki** [comment]
It's just the deployment branch is different than main and the changes are made in main branch.
I'll push the changes to deployment branch once the Hactoberfest is over.
