### ISSUE TITLE
The Banner text is bumping and not coming in one line in mobile devices. 

### ISSUE THREAD

**Issue by Abhishek-465** [lazyjinchuriki/portfolio#6]
DESCRIPTION: The Banner text is bumping and not coming in one line in mobile . 
STEPS TO REPRODUCE:
1) Open the website in mobile phones (screen size -400 to 500 px). 
2) Clearly the problem can be noticed. 
![Screenshot_2023-10-01-20-02-45-701_com android chrome](https://github.com/lazyjinchuriki/portfolio/assets/127030695/b11e2c20-44c8-4e86-bae5-1785e70d352a)

I will work on this issue to rectify the texts and improve the user experience.

**Comment by lazyjinchuriki** [comment]
> DESCRIPTION: The Banner text is bumping and not coming in one line in mobile . 
> STEPS TO REPRODUCE:
> 1) Open the website in mobile phones (screen size -400 to 500 px). 
> 2) Clearly the problem can be noticed. 
> ![Screenshot_2023-10-01-20-02-45-701_com android chrome](https://github.com/lazyjinchuriki/portfolio/assets/127030695/b11e2c20-44c8-4e86-bae5-1785e70d352a)
> 
> I will work on this issue to rectify the texts and improve the user experience. 

Best of luck. 👍🏻
I'll merge it.
