### ISSUE TITLE
Need improvement in responsiveness of Navbar

### ISSUE THREAD

**Issue by imsoumik03** [lazyjinchuriki/portfolio#8]
### Description
Navbar's responsiveness needs some improvement at mobile & tab viewport .
I have already worked on it.

> Then

![Screenshot (50)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/096c3226-84d3-4170-a893-f69486f17065)
![Screenshot (51)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/6d31d4f8-75b9-45e8-8c6f-dd968c8ff76e)

> Now

![Screenshot (52)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/8d0348f7-318c-491d-b512-973cece7a38f)
![Screenshot (53)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/079fcfb3-2f4a-4e37-a406-38fcb42e1e4f)

Can you assign me this issue as a hacktoberfest contributor?

**Comment by lazyjinchuriki** [comment]
> ### Description
> Navbar's responsiveness needs some improvement at mobile & tab viewport .
> I have already worked on it.
> 
> > Then
> 
> ![Screenshot (50)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/096c3226-84d3-4170-a893-f69486f17065)
> ![Screenshot (51)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/6d31d4f8-75b9-45e8-8c6f-dd968c8ff76e)
> 
> > Now
> 
> ![Screenshot (52)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/8d0348f7-318c-491d-b512-973cece7a38f)
> ![Screenshot (53)](https://github.com/lazyjinchuriki/portfolio/assets/123642678/079fcfb3-2f4a-4e37-a406-38fcb42e1e4f)
> 
> Can you assign me this issue as a hacktoberfest contributor?
> 

You need to fork this repo, clone it in your virtual machine, make necessary changes and make a pull request.
I'll definitely merge it. 😄
